server:
  port: 8083

spring:
  session:
    redis:
      flush-mode: on_save
  config:
    activate:
      on-profile: dev

  data:
    redis:
#      cluster:
#        nodes:
#          - localhost:7001
#          - localhost:7002
#          - localhost:7003
#          - localhost:7101
#          - localhost:7102
#          - localhost:7103
#        max-redirects: 1

      host: localhost
      port: 6379

variable:
  clientAddr: http://localhost:3000
  memberReadAddr: http://localhost:8082
  memberAPI: /api/v1/members/member

  kibana: http://localhost:5601
  kafka-ui: http://localhost:8086
  grafana: http://localhost:8087
  argoCD: http://localhost:111111

  role:
    admin: "[ADMIN]"
    user: "[USER]"

  jwt:
    cookieHeader: accessTokenSFG
    secretKey: SeSAC-Five-Guys-Secret-Key-202308TO202401
    access:
      tokenHeader: SeSAC-Five-Guys-Auth
      period: 86400000
      dateFormat: "yyyy-MM-dd-HH-mm-ss"